trigger:
- pipeline

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Trips
    steps:
      - script: |
          docker build --no-cache \
          --build-arg IMAGE_VERSION="1.0" \
          --build-arg IMAGE_CREATE_DATE="`date -u +"%Y-%m-%dT%H:%M:%SZ"`" \
          --build-arg IMAGE_SOURCE_REVISION="`git rev-parse HEAD`" \
          -f dockerfiles/Dockerfile_4 \ 
          -t "tripinsights/trips:1.0" \
          src/trips

          docker save -o $env:BUILD_ARTIFACTSTAGINGDIRECTORY/trips.tar tripinsights/trips:1.0
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: trips

- stage: Test
  displayName: Test stage
  dependsOn: Build
  jobs:
  - job: Test
    steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'trips'
          downloadPath: '$(System.ArtifactsDirectory)'
      - script: |
          docker load < $(System.ArtifactsDirectory)/trips.tar
          docker run -d -n trips tripinsights/trips:1.0
          docker ps
          docker stop trips