trigger:
- pipeline

variables:
  PROJECT_NAME: tripinsights
  SQL_PASSWORD: localtestpw123

jobs:
  - job: Images
    steps:
      - script: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o ./
          ./docker-compose build -f docker-compose.yaml --no-cache \
            --parallel \
            --build-arg IMAGE_VERSION=1.0 \
            --build-arg IMAGE_CREATE_DATE="`date -u +"%Y-%m-%dT%H:%M:%SZ"`" \
            --build-arg IMAGE_SOURCE_REVISION="`git rev-parse HEAD`"
        displayName: 'Build images'
      - script: |
          docker network create $(PROJECT_NAME)
        displayName: 'Create docker network'
      - script: |
          docker run -d \
            --network $(PROJECT_NAME) \
            -e 'ACCEPT_EULA=Y' \
            -e 'MSSQL_SA_PASSWORD=$(SQL_PASSWORD)' \
            --name 'sqltestdb' \
            -p 1433:1433 \
            mcr.microsoft.com/mssql/server:2017-latest

          docker exec sqltestdb /opt/mssql-tools/bin/sqlcmd \
            -S localhost -U SA -P '$(SQL_PASSWORD)' \
            -Q "CREATE DATABASE mydrivingDB"

          docker run -d \
            --network $(PROJECT_NAME) \
            --name dataload \
            --image vyta/data-load:v1 \
            -e "SQLFQDN=sqltestdb" \
            -e "SQLUSER=sa" \
            -e "SQLPASS=$(SQL_PASSWORD)"" \
            -e "SQLDB=mydrivingDB"
        displayName: 'Set up SQL Server'
      - script: | 
          docker run -d \
            --network $(PROJECT_NAME) \
            -p 8080:80 \
            --name poi \
            -e "SQL_PASSWORD=$(SQL_PASSWORD)" \
            -e "SQL_SERVER=sqltestdb" \
            -e "SQL_USER=sa" \
            -e "ASPNETCORE_ENVIRONMENT=Development" \
            tripinsights/poi:1.0

          docker run -d \
            --network $(PROJECT_NAME) \
            -p 8081:80 \
            --name trips \
            -e "SQL_PASSWORD=$(SQL_PASSWORD)" \
            -e "SQL_SERVER=sqltestdb" \
            -e "SQL_USER=sa" \
            -e "DOCS_URI=http://$EXTERNAL_IP" \
            tripinsights/trips:1.0

          docker run -d \
            --network $(PROJECT_NAME) \
            -p 8082:80 \
            --name user-java \
            -e "SQL_PASSWORD=$(SQL_PASSWORD)" \
            -e "SQL_SERVER=sqltestdb" \
            -e "SQL_USER=sa" \
            tripinsights/user-java:1.0 

          docker run -d \
            --network $(PROJECT_NAME) \
            -p 8083:80 \
            --name userprofile \
            -e "SQL_PASSWORD=$(SQL_PASSWORD)" \
            -e "SQL_SERVER=sqltestdb" \
            -e "SQL_USER=sa" \
            tripinsights/userprofile:1.0

          docker ps
        displayName: 'Run Trips docker images'
      - script: |
          curl -s -X GET 'http://localhost:8080/api/poi'
        displayName: 'Run tests'
      - script: | 
          docker stop trips
          docker stop user-java
          docker stop userprofile
          docker stop poi
        displayName: 'Stop Trips docker images'
      